### ISSUE TITLE
兩岸用語差異

### ISSUE THREAD

**Issue by rainfoxest** [bowans/slay-the-spire-zht-localization#30]
ZHS | ZHT | 註
---- | --- | ---
等離子 | 電漿 | 充能球
全息 | 全像 | 機器人卡牌
卡戎 | 凱倫 | 遺物
遞歸 | 遞迴 | 機器人卡牌 (重新生成)
起效 | 生效 | --
盜夢空間 | 全面啟動 | 自訂模式 (電影梗)

**Comment by bowans** [comment]
**等離子**
我本來真的沒注意這是到 ```電漿```，不過用了繁化姬的台灣化後確實也翻回 ```電漿``` 了。

**全息**
上次已改

**卡戎**
上次已改

**遞歸**
是的，這是我們的 ```遞迴``` ，只是原本是 ```Redo```，我沒發現英文改成 ```recursion``` 了

**起效**
改 ```生效``` 合理

**盜夢空間**
我們就是 ```全面啟動``` 囉

**Comment by bowans** [comment]
大致已處理完畢，若還有發現再個別處理。
