### ISSUE TITLE
統計數據中，句尾的全形冒號改用半形

### ISSUE THREAD

**Issue by rainfoxest** [bowans/slay-the-spire-zht-localization#39]
全形:
![20180719132651_1](https://user-images.githubusercontent.com/31983538/42924128-5a6d7d26-8b5b-11e8-9414-8120b94ffefb.jpg)

半形:
![20180719133319_1](https://user-images.githubusercontent.com/31983538/42924163-79d529e8-8b5b-11e8-8db4-1ebda3a1eb39.jpg)

在Windows的UI中冒號都是使用半形，以及在[mozilla的正體中文（台灣）在地化樣式與翻譯規範文件](https://mozilla-l10n.github.io/styleguides/zh-TW/)也有特別提及冒號的使用。

> 無論句子語言為何，句尾冒號使用半形冒號「:」，而非全形冒號「：」。

**Comment by bowans** [comment]
遊戲翻譯的冒號，都是全形的。除了特殊需求像是時間 11:30 這種以外，都是全形的。

我想現在你會覺得全形在這邊會顯示很奇怪，是因為「：」右邊的數字沒有正確的貼在「：」右邊的邊界上。
而這肯定也是 libgdx 無法正確計算中文字寬度的 bug 所造成的。

> 無論句子語言為何，句尾冒號使用半形冒號「:」，而非全形冒號「：」。

可以理解他在這邊想要呈現的，大概是這種感覺
![image](https://user-images.githubusercontent.com/1835103/42956126-c5b956b2-8bb1-11e8-8539-e8754d450d61.png)
但在統計數據這頁也不符合所謂的句尾冒號，這裡的冒號都是在句子正中間。

目前唯一能看到比較接近句尾冒號的只有設定頁 (說接近是因為後面接著下拉式選單)
![image](https://user-images.githubusercontent.com/1835103/42956014-659379e8-8bb1-11e8-9e57-ea12c63ba535.png)
但說真的，就算這邊句尾冒號是全形的也不會感覺奇怪

**Comment by rainfoxest** [comment]
好的。
