### ISSUE TITLE
巨口儲蓄罐

### ISSUE THREAD

**Issue by bowans** [bowans/slay-the-spire-zht-localization#45]
@rainfoxest 我剛好看到你們在 Discord 上的討論。

Maw Bank 既然是一個 piggy bank 的概念，我們似乎應該翻成「巨口存錢桶」或「巨口撲滿」XD

**Comment by rainfoxest** [comment]
都可以。
因為對我來說撲滿, 存錢桶, 儲蓄罐 都是相同的東西，改不改也行。

**Comment by rainfoxest** [comment]
感覺 豬形的(玩偶外形?) 多會叫 撲滿?

**Comment by bowans** [comment]
對阿，撲滿、存錢桶差不多，儲蓄罐也看得懂，只是想想比較少這樣用。
我在問香港朋友的看法，不過對方睡了，之後我再補回答。

**Comment by rainfoxest** [comment]
其實我就是香港那邊。
那邊會用其他粵語，所以不用考慮。

**Comment by bowans** [comment]
我香港朋友也說看得懂撲滿，真神奇。
不過目前這樣，就先不改翻譯了，結案！
