### ISSUE TITLE
介面刪除句末句號

### ISSUE THREAD

**Issue by rainfoxest** [bowans/slay-the-spire-zht-localization#5]
仿爐石的卡牌說明
句末說明刪除句號

如Dev修正了中文 NL 失效的問題
可把 NL 前的句子的句號也刪除，達至每條特效一句，各自句末沒有句號

**Comment by bowans** [comment]
大致上可以跟爐石一樣最後沒有句點。

每條特效一句也不錯，到時候看看有沒有特例不適合這樣做。

**Comment by bowans** [comment]
![image](https://user-images.githubusercontent.com/1835103/42832169-fa86a5ce-8a22-11e8-9650-8cc2913c6ee1.png)
![image](https://user-images.githubusercontent.com/1835103/42832160-ef285dda-8a22-11e8-878c-1073341f831b.png)
![image](https://user-images.githubusercontent.com/1835103/42832181-03539dd8-8a23-11e8-9172-6c4e2437327c.png)

看習慣框框結尾沒句點後，現在連tip的句點都覺得累贅了，甚至覺得兩段的句點都拿掉也可以

**Comment by rainfoxest** [comment]
可以。
當初我沒有改動那文件是因為用取代功能應該會有很多誤傷。

**Comment by bowans** [comment]
大致已處理完畢，若還有發現再個別處理。
