### ISSUE TITLE
精簡說明 - 你、你的

### ISSUE THREAD

**Issue by rainfoxest** [bowans/slay-the-spire-zht-localization#6]
由於此遊戲為單機遊戲，建議精簡卡牌、遺物等等說明中的"你",, "你的", 以更容易閱讀
現時部分卡牌說明太多"你的", 使得閱讀上產生一定困難
只刪除玩家限定的效果或物件
eg. 你的手牌, 你的充能球

敵我共用的名詞則不刪除, eg.
你的回合, 你的生命

**Comment by bowans** [comment]
同意，刪除這些大部分是不影響牌面敘述的。
只是要注意需要保留的部分。

**Comment by bowans** [comment]
大致已處理完畢，若還有發現再個別處理。
